municipal_app/project/__init__.py
# project/__init__.py


#################
#### imports ####
#################

import os
import logging
import sys
import datetime
from flask import Flask, render_template
from flask_login import LoginManager, current_user
from flask_bcrypt import Bcrypt
from flask_mail import Mail, Message
from flask_debugtoolbar import DebugToolbarExtension
from flask_sqlalchemy import SQLAlchemy
from werkzeug.debug import get_current_traceback
from config import ProductionConfig as APP_SETTINGS

################
#### config ####
################

app = Flask(__name__)

# app.config.from_object(os.environ['APP_SETTINGS'])
app.config.from_object(APP_SETTINGS)
# app.debug = True
####################
#### extensions ####
####################

login_manager = LoginManager()
login_manager.init_app(app)
bcrypt = Bcrypt(app)
mail = Mail(app)
toolbar = DebugToolbarExtension(app)
db = SQLAlchemy(app)


####################
#### blueprints ####
####################


from project.subvention.views import subvention_blueprint
from project.fourrier.views import fourrier_blueprint
from project.organigramme.views import organigram_blueprint
from project.passation_marche.views import passmarch_blueprint
from project.permis_construction.views import permisconst_blueprint
from project.budget.views import budget_blueprint
from project.main.views import main_blueprint
from project.user.views import user_blueprint
from project.admin.views import admin_blueprint
from project.municipal_property.views import municipal_property_blueprint
from project.ressource_manager.views import ressource_blueprint
app.register_blueprint(main_blueprint)
app.register_blueprint(subvention_blueprint)
app.register_blueprint(user_blueprint)
app.register_blueprint(admin_blueprint)
app.register_blueprint(budget_blueprint)
app.register_blueprint(fourrier_blueprint)
app.register_blueprint(organigram_blueprint)
app.register_blueprint(passmarch_blueprint)
app.register_blueprint(permisconst_blueprint)
app.register_blueprint(municipal_property_blueprint)
app.register_blueprint(ressource_blueprint)



####################
#### flask-login ####
####################

from project.models import User

login_manager.login_view = "user.login"
login_manager.login_message_category = "danger"


@login_manager.user_loader
def load_user(user_id):
    return User.query.filter(User.id == int(user_id)).first()


def send_log_email(subject, template):
    msg = Message(
        subject,
        html=template,
        recipients=['med@onshor.org'],
        sender=app.config['MAIL_DEFAULT_SENDER']
    )
    mail.send(msg)
########################
#### error handlers ####
########################


@app.errorhandler(403)
def forbidden_page(error):
    auth = True if current_user.__dict__ else False
    return render_template("errors/403.html", auth=auth), 403


@app.errorhandler(404)
def page_not_found(error):
    auth = True if current_user.__dict__ else False
    return render_template("errors/404.html", auth=auth), 404


@app.errorhandler(500)
def server_error_page(error):
    track = get_current_traceback(skip=1, show_hidden_frames=True, ignore_system_exceptions=False)
    html = render_template("errors/error_mail.html", stacktrace=str(track.plaintext))
    try:
        send_log_email(current_user.name + ' ' + current_user.last_name + ' ' + current_user.municipal_id + ' ' + str(datetime.datetime.now()), html)
        auth = True
    except:
        send_log_email('server_error', html)
        auth = False
    return render_template("errors/500.html", auth=auth), 500

municipal_app/project/main/views.py
# project/main/views.py


#################
#### imports ####
#################

from flask import render_template, Blueprint
from flask_login import login_required


################
#### config ####
################

main_blueprint = Blueprint('main', __name__,)


################
#### routes ####
################

@main_blueprint.route('/')
@login_required
def home():
    return render_template('main/index.html')

municipal_app/project/organigramme/views.py
# project/organigramme/views.py
# -*- coding: utf-8 -*

#################
#### imports ####
#################

from project.decorators import check_confirmed
from flask import render_template, Blueprint, url_for, redirect, flash, request
from flask_login import login_required, current_user
from project.models import Organigramme
from project import db, app
import json
import os


################
#### config ####
################

organigram_blueprint = Blueprint('organigramme', __name__,)


################
#### routes ####
################

@organigram_blueprint.route('/organigramme', methods=['GET', 'POST'])
@login_required
@check_confirmed
def organigramme():
    if Organigramme.query.filter_by(municipal_id=current_user.municipal_id).first():
        json_organigramme = json.dumps(Organigramme.query.filter_by(municipal_id=current_user.municipal_id).first().organigramme_data)
        org_id = Organigramme.query.filter_by(municipal_id=current_user.municipal_id).first().id
        update = True
    else:
        json_organigramme = u'{"class": "go.TreeModel","nodeDataArray": [{"key": 1, "name": "(الاسم و اللقب)", "title": "", "email": "", "tel": "", "tel_fixe": ""}]}'
        update = False
    if 'javascript_data' in request.values:
        jdata = json.loads(request.values['javascript_data'])
        if update:
            org = Organigramme.query.get(org_id)
            org.organigramme_data = jdata
            db.session.commit()
        else:
            org = Organigramme(user_id=current_user.id,
                               municipal_id=current_user.municipal_id,
                               organigramme_data=jdata)
            db.session.add(org)
            db.session.commit()
        flash(u'تم تحيين التنظيم الهيكلي', 'success')
    confirm_url = url_for('main.home', _external=True) + 'static/files/'
    org_url = confirm_url + get_json_file(json_organigramme, 'organigramme_' + current_user.municipal_id)
    return render_template('organigramme/organigramme.html', json_organigramme=json_organigramme, org_file=org_url)


def get_json_file(data, ref):
    file_name = ref + '.json'
    filepath = get_file_path() + ref + '.json'
    with open(filepath, 'wb') as outfile:
        json.dump(data, outfile)
    return file_name


def get_file_path():
    if os.path.isdir('project/static/files/'):
        return 'project/static/files/'
    else:
        return "/home/appuser/municipality_tools/municipality_tools/ODMunicipalityTools/municipal_app/project/static/files/"

municipal_app/project/passation_marche/views.py
# project/passation_marche/views.py
# -*- coding: utf-8 -*

#################
#### imports ####
#################

from pprint import pprint as pp
from project.decorators import check_confirmed
from flask import render_template, Blueprint, url_for, redirect, flash, request
from flask_login import login_required, current_user
from parser import parse_passmarch

################
#### config ####
################

passmarch_blueprint = Blueprint('passation_marche', __name__,)
ALLOWED_EXTENSIONS = set(['xml', 'XML'])

################
#### routes ####
################


@passmarch_blueprint.route('/passmarch/adeb/<upload>', methods=['GET', 'POST'])
@passmarch_blueprint.route('/passmarch/adeb')
@login_required
@check_confirmed
def passmarch(upload=None):
    if upload:
        if request.method == 'POST':
            if 'file' not in request.files:
                flash(u'لا يوجد ملف', 'warning')
                return redirect(request.url)
            f = request.files['file']
            if f.filename == '':
                flash(u'لا يوجد ملف', 'warning')
                return redirect(request.url)
            if f and allowed_file(f.filename):
                pp(f.filename)
                pass_march_data = parse_passmarch(f)
                pp(pass_march_data)
                pp(len(pass_march_data))
            else:
                flash(u'صيغة ملف خاطئة ', 'warning')
    return render_template('passation_marche/passation_marche.html')





def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

municipal_app/project/user/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*

import datetime
from project.decorators import check_confirmed
from project.token import generate_confirmation_token, confirm_token
from flask import render_template, Blueprint, url_for, redirect, flash, request
from flask_login import login_user, logout_user, login_required, current_user
from project.models import User, Municipality
from project.email import send_email
from project import db, bcrypt, app
from .forms import LoginForm, RegisterForm, ChangePasswordForm, ContactForm, ApiForm
from pprint import pprint as pp
import ckanapi


################
#### config ####
################

user_blueprint = Blueprint('user', __name__,)
ALLOWED_EXTENSIONS = set(['xml'])

################
#### routes ####
################


@user_blueprint.route('/contact', methods=['GET', 'POST'])
def contact():
    form = ContactForm(request.form)
    if form.validate_on_submit():
        d = {'name': form.name.data,
             'email': form.email.data,
             'tel': form.tel.data,
             'message': form.message.data,
             'municipalite': form.municipalite.data}
        email = "med@onshor.org"
        html = render_template('user/email.html', d=d)
        subject = u"Join demande from municipality  " + d['municipalite']
        send_email(email, subject, html)
        return render_template('user/contact.html', send=True)
    return render_template('user/contact.html', form=form)


@user_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    choices = [{'value': None, 'name': u'المنطقة البلدية'}]
    choices.extend([{'value': _.municipal_id, 'name': _.municipal_name_ar + ' ' + _.municipal_name} for _ in Municipality.query.filter_by(approved=True).all() if _.municipal_id != '1'])
    form = RegisterForm(request.form)
    if form.validate_on_submit():
        if form.municipal_id.data != 'None':
            ckan_name = (form.email.data.split('@')[0] + '_' + form.municipal_id.data).replace('.', '').replace('-', '')
            password = form.password.data
            fullname = form.name.data + ' ' + form.last_name.data
            email = form.email.data
            list_ckan_user = get_list_user()
            ckan_email_list = [_['email'] for _ in list_ckan_user]
            if email in ckan_email_list:
                for e in list_ckan_user:
                    if e['email'] == email:
                        api_dict = e
                        ckan_name = e['name']
            else:
                api_dict = create_user_ckan(ckan_name, password, fullname, email)
            user = User(
                email=form.email.data,
                password=form.password.data,
                name=form.name.data,
                last_name=form.last_name.data,
                municipal_id=form.municipal_id.data,
                confirmed=False,
                deleted=False,
                activate=False,
                last_login=datetime.datetime.now(),
                phone_number=form.phone_number.data,
                work_position=form.work_position.data,
                api_key=api_dict['apikey'],
                ckan_id=api_dict['id'],
                ckan_name=ckan_name
            )
            db.session.add(user)
            db.session.commit()
            token = generate_confirmation_token(user.email)
            confirm_url = url_for('user.confirm_email', token=token, _external=True)
            mun_name = Municipality.query.filter_by(municipal_id=str(form.municipal_id.data)).first().municipal_name
            html = render_template('user/activate.html', confirm_url=confirm_url, name=form.name.data, last_name=form.last_name.data, last_login=datetime.datetime.now(), mun_name=mun_name)
            subject = u"برجاء تأكيد بريدك الالكترونى"
            send_email(user.email, subject, html)
            login_user(user)
            # flash(u'تم إرسال رسالة تأكيد عبر البريد الإلكتروني.', 'success')
            return redirect(url_for("user.unconfirmed"))
        else:
            flash(u'خانة المنطقة البلدية اجبارية', 'warning')
    return render_template('user/register.html', form=form, choices=choices)


@user_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        deleted_list = [_.email for _ in User.query.filter_by(deleted=True).all()]
        panned_list = deleted_list + [_.email for _ in User.query.filter_by(activate=False, confirmed=True).all()]
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(
                user.password, request.form['password']):
            if form.email.data in panned_list:
                flash(u'لقد تم حظرك من المنظومة ,ارجاء الإتصال بمشرف التطبيقه', 'warning')
                return render_template('user/login.html', form=form)
            else:
                login_user(user)
                user.last_login = datetime.datetime.now()
                db.session.commit()
                flash(u'مرحباً', 'success')
                return redirect(url_for('main.home'))
        else:
            flash(u'البريد الإلكتروني  و  أو كلمة المرور  غير صالح', 'danger')
            return render_template('user/login.html', form=form)
    return render_template('user/login.html', form=form)


@user_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash(u'لقد خرجت', 'success')
    return redirect(url_for('user.login'))


@user_blueprint.route('/profile', methods=['GET', 'POST'])
@login_required
@check_confirmed
def profile():
    apiform = ApiForm(request.form)
    form = ChangePasswordForm(request.form)
    mun = Municipality.query.filter_by(municipal_id=current_user.municipal_id).first().municipal_name_ar
    if form.validate_on_submit():
        user = User.query.filter_by(email=current_user.email, last_name=current_user.last_name, name=current_user.name,
                                    municipal_id=current_user.municipal_id).first()
        if user:
            user.password = bcrypt.generate_password_hash(form.password.data)
            db.session.commit()
            flash(u'تم تحيين  كلمة السر', 'success')
            return redirect(url_for('user.profile'))
        else:
            flash('Password change was unsuccessful.', 'danger')
            return redirect(url_for('user.profile'))
    if apiform.validate_on_submit():
        user = User.query.get(current_user.id)
        user.api_key = apiform.api_key.data
        db.session.commit()
        flash(u'تم اضافة / تحيين api key', 'success')
        return redirect(url_for('main.home'))
    return render_template('user/profile.html', form=form, mun=mun, apiform=apiform)


@user_blueprint.route('/confirm/<token>')
@login_required
def confirm_email(token):
    try:
        email = confirm_token(token)
    except:
        flash('The confirmation link is invalid or has expired.', 'danger')
    user = User.query.filter_by(email=email).first_or_404()
    if user.confirmed:
        flash(u'تم تأكيد الحساب بالفعل. الرجاء تسجيل الدخول', 'success')
    else:
        user.confirmed = True
        user.activate = True
        user.confirmed_on = datetime.datetime.now()
        db.session.add(user)
        db.session.commit()
        flash(u'لقد قمت بتأكيد حسابك. شكر!', 'success')
    return redirect(url_for('main.home'))


@user_blueprint.route('/unconfirmed')
@login_required
def unconfirmed():
    if current_user.confirmed:
        return redirect('main.home')
    # flash(u'يرجى تأكيد حسابك!', 'warning')
    return render_template('user/unconfirmed.html')


@user_blueprint.route('/resend')
@login_required
def resend_confirmation():
    token = generate_confirmation_token(current_user.email)
    confirm_url = url_for('user.confirm_email', token=token, _external=True)
    html = render_template('user/activate.html', confirm_url=confirm_url)
    subject = u"تأكيد بريدك الالكترونى"
    send_email(current_user.email, subject, html)
    flash(u'تم إرسال رسالة تأكيد إلكترونية جديدة.', 'success')
    return redirect(url_for('user.unconfirmed'))


def create_user_ckan(name, password, fullname, email):
    ckan = ckanapi.RemoteCKAN(app.config['CKAN_URL'], apikey=app.config['CKAN_API_KEY'])
    user_dict = {'name': name, 'password': password, 'email': email, 'fullname': fullname}
    api_dict = ckan.action.user_create(**user_dict)
    return api_dict


def get_list_user():
    ckan = ckanapi.RemoteCKAN(app.config['CKAN_URL'], apikey=app.config['CKAN_API_KEY'])
    return ckan.action.user_list()

municipal_app/project/templates/user/activate.html
<p>a nouveau membre du municipalitée {{ mun_name }} </p>
<br>
<p>Nom: {{name}}</p>
<br>
<p>Prénom: {{last_name}}</p>
<br>
<p>Date et temps du demande d'accés : {{last_login}}</p>
<p>pour le confirmer cliquez sur le lien si deçue </p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>

municipal_app/project/templates/user/contact.html
<!DOCTYPE html>
<html>   
<head>
  <!-- meta -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Municipalit tools for open data">
  <link rel="shortcut icon" type="image/x-icon" href="http://onshor.org/wp-content/uploads/2017/10/icon.png">
  <meta name="keywords" content="Responsive, HTML5, Municipality, Tunisia, Opendata">
  <title>Municipal app</title>
  <meta name="author" content="med dahas">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <!-- styles -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/plugins/select2/select2.css' ) }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/mouldifi-forms.css' ) }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/entypo.css' ) }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css' ) }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css' ) }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/mouldifi-core.css' ) }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-rtl.min.css' ) }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/mouldifi-rtl-core.css' ) }}">     
</head>
{% block content %}
<body class="login-page">
  <div class="animatedParent animateOnce z-index-50">
    <div class="login-container animated growIn slower">
      <div class="login-content">
        <div class="login-branding">
          <a href="http://onshor.org/"><img src="http://openbaladiati.tn/img/openbaladiati_tn.png" alt="Onshor" title="Onshor"></a>
        </div>
        {% if send %}
        <h3>لقد تم إرسال المطلب بنجاح </h3>
        <p>وسوف يتصل بك فريق أنشر في قريب العاجل</p>
        <p> كما يمكنكم تحميل الاتفاقية النموذجية على هذا <a href='http://app.openbaladiati.tn/static/files/MOU_template.pdf'>الرابط</a></p>
        <!-- 
        <p>إنشاء <a href='/register'>حساب</a></p> -->
        <p><button class='btn btn-info' onclick="goBack()">عد للصفحة السابقة</button></p>
        {% else %}
        <form class="form-signin" role="form" method="post" action="">
            {{ form.csrf_token }}                      
            <div class="form-group">
              {{ form.name(type="text", placeholder="الاسم و اللقب", class="form-control") }}
              {% if form.name.errors %}
              {% for error in form.name.errors %}
              <p style='color:red'>{{ error }}</p>
              {% endfor %}
              {% endif %}
            </div>   
            <div class="form-group">
              {{ form.municipalite(type="text" ,placeholder="االمنطقة البلدية", class="form-control") }}
              {% if form.municipalite.errors %}
              {% for error in form.municipalite.errors %}
              <p style='color:red'>{{ error }}</p>
              {% endfor %}
              {% endif %}
            </div>                     
            <div class="form-group">
              {{ form.email(type="email" ,placeholder="البريد الإلكتروني", class="form-control") }}
              {% if form.email.errors %}
              {% for error in form.email.errors %}
              <p style='color:red'>{{ error }}</p>
              {% endfor %}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.tel(type="text" ,placeholder="رقم الهاتف", class="form-control") }}
              {% if form.tel.errors %}
              {% for error in form.tel.errors %}
              <p style='color:red'>{{ error }}</p>
              {% endfor %}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.message(type="textarea" ,placeholder="الرسالة ", class="form-control", style='height: auto') }}
              {% if form.message.errors %}
              {% for error in form.message.errors %}
              <p style='color:red'>{{ error }}</p>
              {% endfor %}
              {% endif %}
            </div>
            <div class="form-group form-action">
              <button class="btn btn-primary btn-block" type="submit">إرسال المطلب </button>
            </div>                        
          </form>
          <div>
          <p>لمزيد المعلومات  الرجاء الاتصال برنامج أنشر عالبريد الإلكتروني <strong>contact@onshor.org</strong></p>
          <p> كما يمكنكم تحميل الاتفاقية النموذجية على هذا <a href='http://app.openbaladiati.tn/static/files/MOU_template.pdf'>الرابط</a></p>
          <!-- <p>أو بالهاتف القار:  36330375 216+</p>
          <p>أو بالهاتف المحمول:  29761033 216+</p> -->
          <p><button class="btn btn-link btn-outline" onclick="goBack()">عد للصفحة السابقة</button></p>
        </div>
          {% endif %}
          
      </div>
    </div>
  </div>
  {% endblock %}
  <script>
function goBack() {
    window.history.back();
}
</script>
  <!--Load JQuery-->
  <script src="{{ url_for('static', filename='js/jquery.min.js' ) }}"></script>
  <script src="{{ url_for('static', filename='js/plugins/select2/select2.full.min.js' ) }}"></script>
  <!-- Load CSS3 Animate It Plugin JS -->
  <script src="{{ url_for('static', filename='js/bootstrap.min.js' ) }}"></script>
  <script src="{{ url_for('static', filename='js/plugins/css3-animate-it-plugin/css3-animate-it.js')}}" type="text/javascript"></script>
</body>

municipal_app/project/templates/user/email.html
<p>contact from <a href="http://app.openbaladiati.tn/">openbaladiati app/</a></p>
<p>name : {{d['name']}} </p>
<p>municipality : {{d['municipalite']}}</p>
<p>email : {{d['email']}} </p>
<p>tel : {{d['tel']}}<p>
<br>
<p>message : </p>
<p>{{ d['message'] }}<p>

municipal_app/project/templates/user/login.html
<!DOCTYPE html>
<html>   
<head>
      <!-- meta -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="Municipalit tools for open data">
      <link rel="shortcut icon" type="image/x-icon" href="http://onshor.org/wp-content/uploads/2017/10/icon.png">
      <meta name="keywords" content="Responsive, HTML5, Municipality, Tunisia, Opendata">
      <title>Municipal app</title>
      <meta name="author" content="med dahas">
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <!-- styles -->
      <link rel="stylesheet" href="{{ url_for('static', filename='css/mouldifi-forms.css' ) }}">
      <link rel="stylesheet" href="{{ url_for('static', filename='css/entypo.css' ) }}">
      <link rel="stylesheet" href="{{ url_for('static', filename='css/font-awesome.min.css' ) }}">
      <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css' ) }}">
      <link rel="stylesheet" href="{{ url_for('static', filename='css/mouldifi-core.css' ) }}">
      <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-rtl.min.css' ) }}">
      <link rel="stylesheet" href="{{ url_for('static', filename='css/mouldifi-rtl-core.css' ) }}">     
   </head>
<body class="login-page">
  <div class="login-pag-inner">
    {% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="row">
  <div class="col-md-12">
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}">
      <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
      {{message}}
    </div>
    {% endfor %}
  </div>
</div>
{% endif %}
{% endwith %}
    <div class="animatedParent animateOnce z-index-50">
      <div class="login-container animated growIn slower">
        <div class="login-content">
          <div class="login-branding">
            <a href="http://onshor.org/"><img src="http://openbaladiati.tn/img/openbaladiati_tn.png" alt="Onshor" title="Onshor"></a>
          </div>
          <h2><strong>مرحباً </strong>,  الرجاء تسجيل الدخول</h2>
          <form class="form-login" role="form" method="post" action="">
            {{ form.csrf_token }}
            <div class="form-group">
              {{ form.email(type="Email", placeholder="البريد الإلكتروني", class="form-control") }}
              {% if form.email.errors %}
                {% for error in form.email.errors %}
                  <p style='color:red'>{{ error }}</p>
               {% endfor %}
             {% endif %}
            </div>
            <div class="form-group">
              {{ form.password(type="password", placeholder="كلمة المرور", class="form-control") }}
              {% if form.password.errors %}
                {% for error in form.password.errors %}
                    <p style='color:red'>{{ error }}</p>
                {% endfor %}
              {% endif %}
            </div>
          <!--
          <div class="form-group">
            <div class="checkbox checkbox-replace">
                <input type="checkbox" id="remeber">
                <label for="remeber">Remeber me</label>
                </div>
          </div>
        -->
            <div class="form-group">
              <button class="btn btn-primary btn-block" type="submit">تسجيل الدخول</button>
            </div>
            <div class="form-group">
              <p> <a href="/register">إحداث حساب</a></p>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>


  <!-- scripts -->
  <script src="{{ url_for('static', filename='js/jquery.min.js' ) }}"></script>
  <script src="{{url_for('static', filename='js/plugins/css3-animate-it-plugin/css3-animate-it.js')}}"></script>
  <script src="{{ url_for('static', filename='js/bootstrap.min.js' ) }}"></script>
</body>
</html>

municipal_app/project/templates/user/unconfirmed.html
{% extends "_base.html" %}

{% block content %}

<h1>مرحباً بك في فضاء التطبيقات الخاص بالبلديات !</h1>
<br>
<p>لقد تم إرسال المطلب بنجاح </p>
<p>وسيتصل بك فريق ONSHOR في أحسن الأجال </p>
        <!-- <p>وسوف يتصل بك فريق أنشر في قريب العاجل</p> -->
<p>لمزيد المعلومات  الرجاء الاتصال برنامج أنشر عالبريد الإلكتروني <strong>contact@onshor.org</strong></p>
<!--           <p>أو بالهاتف القار:  36330375 216+</p>
          <p>أو بالهاتف المحمول:  29761033 216+</p> -->
<!-- <p>لم أحصل على البريد الإلكتروني? <a href="{{ url_for('user.resend_confirmation') }}">إعادة إرسال</a>.</p>
 -->
{% endblock %}